### ISSUE TITLE
Base64 key no longer works

### ISSUE THREAD

**Issue by aaronlestones** [ayush1920/Multcloud_remote_upload#3]
It seems that the base64 AES key can no longer decrypt the encrypted response.

**Comment by jimtje** [comment]
LIa4CTfB3SwKnfJhu2iJkQ== is the current decrypt key. If you need to encrypt and not use a salt, the encrypt key is KXrDPHUkQSMKhklkKHHP+Q==

**Comment by aaronlestones** [comment]
> LIa4CTfB3SwKnfJhu2iJkQ== is the current decrypt key. If you need to encrypt and not use a salt, the encrypt key is KXrDPHUkQSMKhklkKHHP+Q==

Thanks, @jimtje!

**Comment by aaronlestones** [comment]
Hi, @jimtje. Are you still able to login to Multcloud using HTTP(S) request? I've been trying to login using email address, password, language, etc.. and signed it with AES, but I keep getting 401 unauthorized. I'm 100% sure email and password are correct as I'm able to login to the web. Any help will be appreciated.

**Comment by jimtje** [comment]
> Hi, @jimtje. Are you still able to login to Multcloud using HTTP(S) request? I've been trying to login using email address, password, language, etc.. and signed it with AES, but I keep getting 401 unauthorized. I'm 100% sure email and password are correct as I'm able to login to the web. Any help will be appreciated.

Have you tried using https://www.multcloud.com/api/user/sign_in_ (yes, with the underscore in the end) to send the POST request? They keep fiddling with their site so I mostly just use rclone now since the site forces the user to not automate, which is both somewhat ironic considering what the site itself does and also, since it clearly has a REST-like interface (possibly Spring Boot?) as the underlying architecture which would also mean that it should be trivial to provide an openapi/swagger endpoint testing page, but nope. 

Also, judging by what's in the JWT that's returned, I have a suspicion that they have some sort of self-rolled oauth2 flow that might be insecure.  But the chances of them having a bug bounty program is pretty much exactly zero so there's no point poking around and checking for potential weaknesses. I just disconnected anything important from my account instead. I'd at least be somewhat wary in terms of linking anything critical to their system. It's somewhat reflective of... something that I don't really know how to express in English without inadvertently making it an ethnic thing when really it's a problem with the state apparatus and the culture that stems from it that coupled with the respectability associated with hierarchy creates a doom loop of performative competence over substantive security. And even the self-aware tend to acquiesce when there's no real alternative. I'm just speculating in this specific case, but being from the country and seeing that sort of risk assessment take place from a place of privilege at every level makes me very wary of how much security through obscurity represents an oversized role in what they sell as security, because there's no real reason for any of that to even exist if you think about it except that it's the sort of performance that is rewarded by the party and all the way down. Be careful, that's all.
